### ISSUE TITLE
Error when trying MII with dtype=fp32 with sampling

### ISSUE THREAD

**Issue by marshmellow77** [microsoft/DeepSpeed-MII#101]
When running the example from https://github.com/microsoft/deepspeed-mii#deploying-mii-public in `fp32` I receive an `AioRpcError` error. See this [notebook](https://github.com/marshmellow77/mii-testing/blob/main/2a_fp32_sampling.ipynb) for a minimal example to reproduce the error.

- 1 T4, GPU memory 16GB
- deepspeed-mii version 0.0.3
- transformers version 4.24.0
- Amazon Linux 2

**Comment by mrwyattii** [comment]
please see https://github.com/microsoft/DeepSpeed-MII/issues/102#issuecomment-1322782384

**Comment by marshmellow77** [comment]
Makes sense.
