### ISSUE TITLE
Add release tag 0.05

### ISSUE THREAD

**Issue by mallorbc** [microsoft/DeepSpeed-MII#128]
I noticed version.txt is at 0.05 but there is no release tag for 0.05 and PyPI is at 0.04.  This change was made over a month ago.  Perhaps there was meant to be a release tag but for some reason, it was forgotten?

**Comment by mrwyattii** [comment]
@mallorbc this is not a mistake. We increment `version.txt` after each release because the commits added between 0.0.4 and 0.0.5 will be part of the 0.0.5 release. 0.0.5 has not been released yet.
