### ISSUE TITLE
Unable to execute mii-sd.py in benchmark

### ISSUE THREAD

**Issue by Yanxing-Shi** [microsoft/DeepSpeed-MII#141]
https://github.com/microsoft/DeepSpeed-MII/blob/main/examples/benchmark/txt2img/mii-sd.py
Hi, I encountered the following error when running the `mi-sd.py` file
`AssertionError: text-to-image only supports ['Xibanya/sunset_city']`
How to solve the problem?

Setup:
deepspeed==0.8.0
deepspeed-mii==0.0.4
diffusers==0.9.0

**Comment by mrwyattii** [comment]
Hi @Yanxing-Shi this error often pops up if you haven't updated `huggingface_hub` or `diffusers` packages. Could you please update those and try again? Thanks!
`pip3 install -U diffusers huggingface_hub`

**Comment by Yanxing-Shi** [comment]
ok，@Einsum thank you！The problem is solved.
