### ISSUE TITLE
HF API calls

### ISSUE THREAD

**Issue by satpalsr** [microsoft/DeepSpeed-MII#186]
This line 
https://github.com/microsoft/DeepSpeed-MII/blob/9527eb5d39fc93ede11c4761abbc13fe7e644795/mii/utils.py#L82

causes
```
huggingface_hub.utils._errors.HfHubHTTPError: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/models
```
if multiple calls are made.

May be models list should be cached instead of making calls again.

**Comment by mrwyattii** [comment]
@satpalsr interesting, we have not run into this issue before. Can you share some more details, like how many times (and in what time frame) you are launching an MII deployment?

I will investigate how we can cache these values for MII and share a PR soon. Thanks!
