### ISSUE TITLE
load_models() missing 1 required positional argument: 'provider'

### ISSUE THREAD

**Issue by adutwumk** [microsoft/DeepSpeed-MII#207]
Hello, I have deploy bloom-560m and save it in folder. I'm trying to start the server without having to use mii.deploy again.
Here is code to start the server

```python
import mii
server = mii.MIIServerClient(
    task_name="text-generation",
    model_name="bigscience/bloom-560m",
    model_path="/tmp/mii_models",
)._initialize_service()
```
but I get this error message
`TypeError: load_models() missing 1 required positional argument: 'provider'`

Do I have to call the `load_model` first or is there another way I can initialize the services?

**Comment by mrwyattii** [comment]
Hi @adutwumk you likely need to add `provider="huggingface"` to the kwargs. Could you help me better understand why you want to avoid using `mii.deploy` again?

**Comment by adutwumk** [comment]
@mrwyattii I want to avoid using mii.deploy more than once. When I run the mii.deploy, it deploy it my local and save the deployment. I dont want to run mii.deploy everytime just to do query.

I want to run this example code

```python 
import mii
generator = mii.mii_query_handle("bloom560m_deployment")
result = generator.query({"query": ["DeepSpeed is", "Seattle is"]}, do_sample=True, max_new_tokens=30)
print(result)
```

Without having to call mii.deploy

I get a error message about server need to start  when I run above code without running mii.deploy first

If you have example how you can use already saved deployment and run query, I will really appreciate it

**Comment by mrwyattii** [comment]
@adutwumk MII was not really designed to be used in this way. We have to run `mii.deploy` to stand up an inference server with the model. Once it is deployed we can run queries on the model. But without running `deploy`, there will be no model loaded!

**Comment by mrwyattii** [comment]
@adutwumk I believe I have answered your questions - but please reopen if you have additional questions about how to use MII. Thank you
