### ISSUE TITLE
Is deepspeed-mii meant to run in a notebook?

### ISSUE THREAD

**Issue by qrdlgit** [microsoft/DeepSpeed-MII#241]
I saw this open issue here - https://github.com/microsoft/DeepSpeed-MII/issues/100

`I can confirm I'm seeing the same behavior when running inside a notebook. In its current state, MII wasn't designed with the intention of running it in a notebook`

However, I became aware of this project because of suggestion on an issue here on deepspeed main - https://github.com/microsoft/DeepSpeed/issues/4294

`As I suggested before, [DeepSpeed-MII](https://github.com/microsoft/DeepSpeed-mii) may be exactly what you are looking for. With DeepSpeed-MII, you can create models sharded across multiple GPUs and do inference all from a single process. This library takes care of the hard bits involved with managing multiple processes. Here's a sample of what you would run from a single process (e.g., a jupyter notebook):`

?

**Comment by qrdlgit** [comment]
I ran the example on a kaggle.com (p100) notebook from that issue but I get this error:
```

RuntimeError                              Traceback (most recent call last)
Cell In[4], line 10
      8 # Run inference
      9 generator = mii.mii_query_handle("my_mii_deployment")
---> 10 result = generator.query({"query": ["The meaning of life is"]})
     11 print(result.response)
     13 # Shut down inference server

File /opt/conda/lib/python3.10/site-packages/mii/client.py:74, in MIIClient.query(self, request_dict, **query_kwargs)
     73 def query(self, request_dict, **query_kwargs):
---> 74     return self.asyncio_loop.run_until_complete(
     75         self._request_async_response(request_dict,
     76                                      **query_kwargs))

File /opt/conda/lib/python3.10/asyncio/base_events.py:625, in BaseEventLoop.run_until_complete(self, future)
    614 """Run until the Future is done.
    615 
    616 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    622 Return the Future's result, or raise its exception.
    623 """
    624 self._check_closed()
--> 625 self._check_running()
    627 new_task = not futures.isfuture(future)
    628 future = tasks.ensure_future(future, loop=self)

File /opt/conda/lib/python3.10/asyncio/base_events.py:584, in BaseEventLoop._check_running(self)
    582 def _check_running(self):
    583     if self.is_running():
--> 584         raise RuntimeError('This event loop is already running')
    585     if events._get_running_loop() is not None:
    586         raise RuntimeError(
    587             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running
```

**Comment by mrwyattii** [comment]
Hi @qrdlgit, the suggested solution in #100 still works for me. Can you try again after restarting the Jupyter kernel and making sure that no background mii processes are still alive from a previous deployment?

Unfortunately, we do not currently have the bandwidth to further investigate a fix for running in a Jupyter Notebook, but we are happy to review contributions if you would like to create a PR!
