### ISSUE TITLE
Add ability to configure temperature, top P, top K, number of beams

### ISSUE THREAD

**Issue by ttim** [microsoft/DeepSpeed-MII#261]
I didn't find a way to configure all of the configuration options below:
- temperature
- top P
- top K
- number of beams

Are there ways to do it? If not are they expected to be added?

**Comment by mrwyattii** [comment]
Hi @ttim, I am currently working to expose temperature, top P, and top K settings. We will provide an update later this week. We do not currently support beam search.

**Comment by mrwyattii** [comment]
This feature will be added when we merge #268
