### ISSUE TITLE
Installed CUDA version 11.7 does not match torch version

### ISSUE THREAD

**Issue by frankxyy** [microsoft/DeepSpeed-MII#277]
Hi，I installed DeepSpeed-MII by pip3 install deepspeed-mii and than infer.

This error is showed.
<img width="1439" alt="image" src="https://github.com/microsoft/DeepSpeed-MII/assets/6971044/e98fd133-2fab-40b6-8e4f-24f95176c70f">

My nvidia config is:
<img width="863" alt="image" src="https://github.com/microsoft/DeepSpeed-MII/assets/6971044/a9407c74-ecc2-4ea4-9eb6-5893b71576b6">

My OS is:
<img width="875" alt="image" src="https://github.com/microsoft/DeepSpeed-MII/assets/6971044/061711bc-df9b-4872-bd96-4c441d704e9d">

**Comment by frankxyy** [comment]
> Hi @frankxyy, as the error message implies we do not support mismatched CUDA versions. Your system version is 11.7 but the version that pytorch was compiled with is 12.1. You must make the major version for those two match. The easiest way to do this is by uninstalling pytorch and installing a version that was compiled with `11.x`. For example:
> 
> ```shell
> pip3 uninstall torch torchaudio torchvision -y
> pip3 install torch --index-url https://download.pytorch.org/whl/cu118
> ```

Got it. Thank u a lot.

**Comment by mrwyattii** [comment]
Issue appears resolved. Closing, but please reopen if this was not the fix.
