### ISSUE TITLE
How to select specific gpu index when using tensor parallel?

### ISSUE THREAD

**Issue by frankxyy** [microsoft/DeepSpeed-MII#283]
Hi，I use the command `CUDA_VISIBLE_DEVICES=1,3 deepspeed --num_gpus 2 infer.py`, but the program is still running on gpu 0 and gpu 1.  The same problem also happens when I try to use persistent serving. So how can I arbitrarily select specific gpu index?

**Comment by mrwyattii** [comment]
Hi @frankxyy, this is a feature we have not brought into the latest MII release, but it is available in MII-Legacy via the [deploy_rank](https://github.com/microsoft/DeepSpeed-MII/blob/870c9d74595d924743c5c5bd0f5348d55ab5eda4/mii/legacy/config.py#L71) option in `mii_config`. I will work to bring this functionality into the latest release. Look for updates soon, thanks!

**Comment by yaof20** [comment]
Thx for your wonderful work. 

I have the same issue. It would be great to see this feature in the latest release! 

Please let me know when it comes true :)
