### ISSUE TITLE
cannot send top_p temperature parameters through client.generate api calling

### ISSUE THREAD

**Issue by frankxyy** [microsoft/DeepSpeed-MII#292]
Hi，I pass top_p、temperature parameters when calling api client.generate like this:

`response = client.generate(prompt[:10], max_new_tokens=4096, top_p=0.95, \
                           temperature=0.1)`

However, the server outputs error below:
<img width="1440" alt="image" src="https://github.com/microsoft/DeepSpeed-MII/assets/6971044/27522714-5908-41ce-b9f6-ac8c46b4e75c">

**Comment by mrwyattii** [comment]
Hi @frankxyy can you verify that you are using the latest release of MII? These parameters were only added in `v0.1.1`

**Comment by ChuanhongLi** [comment]
> Hi @frankxyy can you verify that you are using the latest release of MII? These parameters were only added in `v0.1.1`

I have met the same problem when using  v0.1.1
![image](https://github.com/microsoft/DeepSpeed-MII/assets/90491543/b352044c-a939-4bd2-bf1f-2c68c68a8bed)

When ignoring thers parameters, it is OK! 
![image](https://github.com/microsoft/DeepSpeed-MII/assets/90491543/364f44d3-5f37-43cf-9119-799a7633567b)

**Comment by mrwyattii** [comment]
This error should be resolved in the latest DeepSpeed-MII. Please reopen the issue if you still see this error. Thanks.
