### ISSUE TITLE
How to get num_of_new_tokens while calling client.generate()

### ISSUE THREAD

**Issue by frankxyy** [microsoft/DeepSpeed-MII#298]
Hi, I called client.generate(xxx) and get this struct:
<img width="439" alt="image" src="https://github.com/microsoft/DeepSpeed-MII/assets/6971044/dc1c86c9-fadc-4cf7-b00d-e864a9b31ef0">

I also want to get the number of tokens in the results. How can I get it? Thank u!

**Comment by mrwyattii** [comment]
Hi @frankxyy, I am actively working on updating the outputs that `client.generate()` returns to include additional information, like `num_tokens_generated`, `stop_reason`, etc.

This update will be included in #295 if you want to track the progress. I will have it merged later this week!

**Comment by frankxyy** [comment]
@mrwyattii got it, thank you!

**Comment by mrwyattii** [comment]
@frankxyy this feature has now been merged. You will need the latest source builds of each library:
```bash
pip install git+https://github.com/microsoft/DeepSpeed.git
pip install git+https://github.com/microsoft/DeepSpeed-MII.git
```

The output from `client.generate` will be a list of `Response` objects (these have `generated_text`, `finish_reason`, `prompt_length`, and `generated_length` attributes that you can access):
```python
outputs = client.generate(["DeepSpeed is", "Seattle is"])
for o in outputs:
    print("generated text: {o.generated_text}, prompt length: {o.prompt_length}, generated length: {o.generated_length}")
