### ISSUE TITLE
[Serving Stability] one request crashed, other requests can not be posted

### ISSUE THREAD

**Issue by frankxyy** [microsoft/DeepSpeed-MII#299]
Hi, I found that when one request processing crashed, other requests can not be posted normally. The client script is stuck when calling client.generate.

**Comment by mrwyattii** [comment]
Can you share the stack trace of the error that causes the process to crash? If it's the server process that crashes, we do not automatically restart the server, which is one reason why the client script may get stuck.

**Comment by frankxyy** [comment]
@mrwyattii OK，I will pay attention to the server log when the client is stuck next time.
