### ISSUE TITLE
how to understand and choose the appropriate max_ragged_batch_size for optimal performance?

### ISSUE THREAD

**Issue by kingder** [microsoft/DeepSpeed-MII#300]
I noticed that the max_ragged_batch_size is set to [768 by default](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/inference/v2/ragged/manager_configs.py#L126). Is this a universally suitable value for all models and GPUs, or is it advisable to manually choose the value for each specific model and GPU configuration and how?

Additionally, under the current settings, it appears that the dynamic splitfuse only needs to split one request each time, specifically the last one that cannot fit into the max_ragged_batch_size. Can you confirm if my understanding of this process is accurate?

Thanks

**Comment by mrwyattii** [comment]
Hi @kingder, please refer to this answer in another issue regarding how to understand `max_ragged_batch_size`: https://github.com/microsoft/DeepSpeed-MII/issues/285#issuecomment-1808599357

@cmikeh2 or @tohtana can you please help respond to the second question about Splitfuse?

**Comment by cmikeh2** [comment]
768 should work well for most models, but depending on the workload it can make sense to increase (maximum throughput is the desire) or decrease (tradeoff throughput at load for better generation latency). We found that 768 is a good balance for most model/hardware configurations though.

For number of requests split, you are correct that currently it will only split 1. There is a theoretical scheduling decision to be made here; if the `max_ragged_batch_size` is 768 and there are two sequences of 512 tokens, one could either schedule 2x 384 (2 splits) tokens or 1x512 + 1x256 (1 split). The second approach minimizes KV-cache occupancy slightly better and so it is always preferred.

**Comment by kingder** [comment]
Thanks for the clarification!
