### ISSUE TITLE
could add `trust_remote_code=True` into `AutoTokenizer.from_pretrained(tokenizer)`

### ISSUE THREAD

**Issue by nlp4whp** [microsoft/DeepSpeed-MII#312]
I notice there's [request-203](https://github.com/microsoft/DeepSpeed-MII/pull/203) which add `trust_remote_code` into `class ModelConfig`
but in main branch, `ModelConfig` doesn't have it, and also `load_tokenizer()` won't use it

so could I have any way to load custom tokenizer for now ?

**Comment by mrwyattii** [comment]
Hi @nlp4whp #203 modified the MII-Legacy code. The recent v0.1.0 release was a complete redesign of MII, so we are still missing a few features that MII-Legacy has. I will create a PR to add this support and share an update soon. Thanks.
