### ISSUE TITLE
Why is the throughput of mii lower than that of vllm in actual measurements?

### ISSUE THREAD

**Issue by pangr** [microsoft/DeepSpeed-MII#314]
Why is the throughput of mii lower than that of vllm in actual measurements? Are there any parameters that need to be configured? Is SplitFuse used by default?

**Comment by PawanOsman** [comment]
I tried it, and responded to 200 requests in ~30 seconds, 
I did the same test with vLLM and responded to 200 requests in ~100 seconds

I sent all the requests together at the same time (NOT one by one)

**Request prompt length**: `2k token`
**Max new tokens**: `128 token`
**GPU**: `1x A6000 48GB`
**Model**: `mistralai/Mistral-7B-v0.1`

**Comment by mrwyattii** [comment]
> Why is the throughput of mii lower than that of vllm in actual measurements? Are there any parameters that need to be configured? Is SplitFuse used by default?

@pangr SplitFuse is used by default - but the way you run your benchmark will matter. Specifically, in our [FastGen Blog Post](https://github.com/microsoft/DeepSpeed/blob/master/blogs/deepspeed-fastgen/README.md) we are using the persistent deployment (i.e., `mii.serve()`) and sending requests from multiple clients at the same time to simulate the application workloads we expect.

As @PawanOsman pointed out, you can also send multiple requests at once from a single client: `client.generate([prompt_1, prompt_2, ...])` (But this will also deviate from what we expect in real-world application workloads)

**Comment by pangr** [comment]
> > Why is the throughput of mii lower than that of vllm in actual measurements? Are there any parameters that need to be configured? Is SplitFuse used by default?
> 
> @pangr SplitFuse is used by default - but the way you run your benchmark will matter. Specifically, in our [FastGen Blog Post](https://github.com/microsoft/DeepSpeed/blob/master/blogs/deepspeed-fastgen/README.md) we are using the persistent deployment (i.e., `mii.serve()`) and sending requests from multiple clients at the same time to simulate the application workloads we expect.
> 
> As @PawanOsman pointed out, you can also send multiple requests at once from a single client: `client.generate([prompt_1, prompt_2, ...])` (But this will also deviate from what we expect in real-world application workloads)

What I tested was the restful_api interface, and the concurrency was 10

**Comment by mrwyattii** [comment]
@pangr we only recently added the RESTful API and we have not done performance benchmarking there. Under the hood, the RESTful API is doing the same thing as when we access the model via a `mii.client()` object. My best guess is that there is some additional overhead from the RESTful API that we may be able to improve in the near future. I will look into it!

**Comment by mrwyattii** [comment]
@pangr please try with the latest `main` branch. I have made improvements that allow us to match performance the RESTful API to our Python API (see #328).

**Comment by mrwyattii** [comment]
#328 has been merged and resolved the lower performance problems. Please reopen this issue if you do not see an improvement. Thanks!
