### ISSUE TITLE
Is possible to add input_tokens length and the output_tokens length in the reponse?

### ISSUE THREAD

**Issue by flexwang** [microsoft/DeepSpeed-MII#320]
Alternative is that we could call tokenizer again on request/response path, but it would be helpful if we can just get that from response.

**Comment by mrwyattii** [comment]
I have added this in #295. I still need to fix one bug in this PR, but once that is complete I will have it merged (hopefully by end of today!)

**Comment by mrwyattii** [comment]
@flexwang you will need to install the latest source builds of DeepSpeed and MII, but this information is now included in the output:
```bash
pip install git+https://github.com/microsoft/DeepSpeed.git
pip install git+https://github.com/microsoft/DeepSpeed-MII.git
```

```python
outputs = client.generate(["DeepSpeed is", "Seattle is"])
for o in outputs:
    print("generated text: {o.generated_text}, prompt length: {o.prompt_length}, generated length: {o.generated_length}")
