### ISSUE TITLE
Low throughput (0.61 reqs/sec) when served with RESTful API 

### ISSUE THREAD

**Issue by noiji** [microsoft/DeepSpeed-MII#325]
What I'm trying to do is to measure the requests mii can handle per second.

So I have started the server with the following code,
```
client = mii.serve(
            model_path,
            deployment_name=deployment_name,
            enable_restful_api=True,
            restful_api_port=8080,
)
```

and sent 10 requests to the localhost endpoint asynchronously.
(A request is composed of one prompt, to reflect real-world use case.)

What I'm seeing as a result is that only **0.61 requests** are processed per second, which is pretty low to what I have expected after seeing what's written in [blog](https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fastgen#4-performance-evaluation--).

Maybe rest api is processing the requests sequentially, not asynchronously?

**Comment by mrwyattii** [comment]
@noiji please try with the latest `main` branch. I have made improvements that allow us to match performance the RESTful API to our Python API (see #328).

**Comment by noiji** [comment]
Thanks for the update!

When run with default(32) restful processes, I see that throughput increases to 3.59 req/s, which is six times bigger than original throughput (0.62/s).

**Comment by mrwyattii** [comment]
Glad to hear! Closing the issue, but please open a new issue if you see any other problems.
