### ISSUE TITLE
mii.serve vs mii.client

### ISSUE THREAD

**Issue by flexwang** [microsoft/DeepSpeed-MII#332]
What is the relationship between `mii.serve` vs `mii.client`? 
Looking at the examples at [here](https://github.com/microsoft/DeepSpeed-MII#persistent-deployment), we can:

- use `client = mii.serve(...` to create a client and do `client.generate`
- we can also do `mii.server` and then `client = mii.client`

what is the difference?
Also, my understanding for `mii.client` is that, it will only handle requests sequentially, so if we only create a single `mii.client`, there will not be continous batching enabled.

**Comment by mrwyattii** [comment]
Both `mii.serve` and `mii.client` will return an `MIIClient` object. The difference is that `mii.serve` is also standing up a persistent deployment server (and then returning a client for interacting with that server) while `mii.client` is only returning the `MIIClient` for an existing server. This is useful when you have multiple processes that need to send prompts to a single server.

For the continuous batching, you are partially correct. Batching will still take place if you send multiple prompts (e.g., `client.generate([prompt1, prompt2, prompt3])`), but you will not receive a reply until all generation is completed.

Please let me know if you have any other questions!

**Comment by flexwang** [comment]
@mrwyattii thanks for the quick reply.
Just to confirm if I understand, if I have more than one customers sending single prompt at roughly the same time(but not exact the same time, so I cannot do `client.generate([prompt1, prompt2, prompt3])`), the correct way to trigger continous batching is through:

1. `mii.serve`;
2. create multple clients by calling `mii.client`

**Comment by mrwyattii** [comment]
That is correct. The multiple clients should each be on separate processes as well.
