### ISSUE TITLE
Error messages spilled from persistent deployment for every request

### ISSUE THREAD

**Issue by weiqisun** [microsoft/DeepSpeed-MII#349]
Hi, in the latest release with version `0.1.2`, the persistent server returns responses with more details, including `prompt_length`, `generated_length`, and `finished_reason`. This is awesome and super useful. Thanks for the updates! However, now the persistent server throws error messages on every request:

```
Traceback (most recent call last):
  File "/home/dyheal1/mambaforge/envs/test/lib/python3.10/site-packages/grpc/_server.py", line 552, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/dyheal1/mambaforge/envs/test/lib/python3.10/site-packages/mii/grpc_related/modelresponse_server.py", line 96, in GeneratorReply
    return task_methods.pack_response_to_proto(responses)
  File "/home/dyheal1/mambaforge/envs/test/lib/python3.10/site-packages/mii/grpc_related/task_methods.py", line 85, in pack_response_to_proto
    finish_reason=str(r.finish_reason.value),
AttributeError: 'NoneType' object has no attribute 'value'
```

I can still get valid responses back, with correct `generated_text`, `finish_reason` etc. But it will be great to eliminate this error message on the server side. For now as a hacky workaround, I modified line 85 in `grpc_related/task_methods.py` to `finish_reason=str(r.finish_reason.value) if r.finish_reason is not None else "none"`.

Here is my setup. I started the persistent server by:
```python
mii.serve(
    "meta-llama/Llama-2-70b-hf",
    deployment_name="mii-endpoint",
    max_length=4096,
    tensor_parallel=2,
)
```

And I call the server using:
```python
client = mii.client("mii-endpoint")
response = client.generate("DeepSpeed is", max_new_tokens=50)
```

Then I will get the error message on the server side. I'm running this on 2 A100-80GB GPUs and the related module versions are:
```
mii: 0.1.2
deepspeed: 0.12.4
torch: 2.0.1
CUDA: 11.8
```

Any help will be appreciated and thanks again for the awesome tool you have built!

**Comment by thelongestusernameofall** [comment]
遇到了同样的问题。

**Comment by mrwyattii** [comment]
@weiqisun I have a fix in #350. If you would like to try that branch before we merge: `pip install git+https://github.com/Microsoft/DeepSpeed-MII@mrwyattii/fix-return-error`

**Comment by weiqisun** [comment]
Thanks @mrwyattii! However, I'm still seeing this error message. I confirm I installed the module from your branch since I have the updated `_invoke_async` function now in the installed lib file.

**Comment by mrwyattii** [comment]
Great to hear. Closing the issue, but please reopen (or create a new issue) if you see this behavior return. I will get this merged into the `main` branch and it will be part of the next MII release.
