### ISSUE TITLE
Unable to run inference on free tier Colab.

### ISSUE THREAD

**Issue by sudhir2016** [microsoft/DeepSpeed-MII#393]
I tried running this quick start code on free tier Colab.

import mii
pipe = mii.pipeline("mistralai/Mistral-7B-v0.1")
response = pipe(["DeepSpeed is", "Seattle is"], max_new_tokens=128)
print(response)

Got this error

RuntimeError: Unable to load ragged_device_ops op due to no compute capabilities remaining after filtering

**Comment by mrwyattii** [comment]
Hi @sudhir2016 What GPU are you trying to run on? I suspect it does not have compute capability >=8.0

**Comment by sudhir2016** [comment]
I was using T4 which is only 7.5 !

**Comment by mrwyattii** [comment]
Unfortunately, we are unable to support GPUs without >= 8.0 CUDA compute capability for the latest DeepSpeed-MII. However, we still support these older architectures within [MII Legacy](https://github.com/microsoft/DeepSpeed-MII/tree/main/mii/legacy).

**Comment by sudhir2016** [comment]
Ok thanks.
