### ISSUE TITLE
ModuleNotFoundError: No module named 'mii'

### ISSUE THREAD

**Issue by bao-xiaoyi** [microsoft/DeepSpeed-MII#398]
deepspeed                 0.13.0
deepspeed-kernels         0.0.1.dev1698255861
deepspeed-mii             0.2.0

but 

ModuleNotFoundError: No module named 'mii'

**Comment by mrwyattii** [comment]
Hi @bao-xiaoyi is this what happens when you do `import mii`?

**Comment by bao-xiaoyi** [comment]
> Hi @bao-xiaoyi is this what happens when you do `import mii`?

The problem has been resolved, thank you
