### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got bool

### ISSUE THREAD

**Issue by SiriusWy** [microsoft/DeepSpeed-MII#405]
I encountered an error using the following code

```python
import mii
client = mii.serve("/home/models/qwen_14b_chat")
response = client.generate(["Deepspeed is", "Seattle is"], max_new_tokens=128)
print(response)
```

TypeError: expected Tensor as element 0 in argument 0, but got bool

**Comment by mrwyattii** [comment]
@SiriusWy This error should be fixed in #408. You can try it locally before we merge:
`pip install git+https://github.com/microsoft/DeepSpeed-MII@mrwyattii/fix-missing-eod-token`
