### ISSUE TITLE
Workarounds for pre-Ampere devices

### ISSUE THREAD

**Issue by jinhachung** [microsoft/DeepSpeed-MII#437]
I understand DeepSpeed-MII is using DeepSpeed-Kernels (which only supports NVIDIA GPUs with compute capability 8.0+) as the backend library. Are there any suggested ways to work around using DeepSpeed-Kernels for people like myself who have access to Volta devices (7.0) or lower?

**Comment by mrwyattii** [comment]
Unfortunately the changes needed to support <8.0 compute capability are extensive. We still support Volta devices with MII-Legacy: https://github.com/microsoft/DeepSpeed-MII/tree/main/mii/legacy
