### ISSUE TITLE
Quantization inference

### ISSUE THREAD

**Issue by freQuensy23-coder** [microsoft/DeepSpeed-MII#439]
In your presentation I see, that deepspeed can support inference of quantizationed models.  But i  have't found any references or examples in documentation.

Are this feature avalibale now (for mixtral model). Where can i find documentation for this feature.

**Comment by mrwyattii** [comment]
@freQuensy23-coder my apologies - we did not update the documentation to reflect the added quantization feature. We currently only support a single quantization mode (read more about that [here](https://github.com/microsoft/DeepSpeed/blob/master/blogs/deepspeed-fp6/03-05-2024/README.md)).

However, I do not think that it is working for all layers in the Mixtral model. I will ask the team that developed the FP6 quantization to follow up on adding Mixtral support. If you wish to try it with other models, here is a sample code:

```python
import mii
pipe = mii.pipeline("NousResearch/Llama-2-70b-hf", quantization_mode='wf6af16')
response = pipe(["DeepSpeed is", "Seattle is"], max_new_tokens=128)
print(response)
```

**Comment by xiaoxiawu-microsoft** [comment]
@freQuensy23-coder  My other thread https://github.com/microsoft/DeepSpeed-MII/issues/440
