### ISSUE TITLE
deepseed-mii支持多节点推理么

### ISSUE THREAD

**Issue by JKYtydt** [microsoft/DeepSpeed-MII#501]
```[tasklist]
### Tasks
```

**Comment by JKYtydt** [comment]
若我有两台机器，每个机器分别有2个GPU，如何实现多节点推理

**Comment by loadams** [comment]
Hi @JKYtydt - the tutorial on inference for DeepSpeed [here](https://www.deepspeed.ai/tutorials/inference-tutorial/#launching) includes directions on how to invoke DeepSpeed such that it can support multi-node inference.
