### ISSUE TITLE
Import Error, not compatible with transformer package

### ISSUE THREAD

**Issue by tang-t21** [microsoft/DeepSpeed-MII#502]
File "/home/Qwen/infer.py", line 63, in <module>
    import mii
  File "/usr/local/lib/python3.10/dist-packages/mii/__init__.py", line 7, in <module>
    from .legacy import MIIServer, MIIClient, mii_query_handle, deploy, terminate, DeploymentType, TaskType, aml_output_path, MIIConfig, ModelConfig, get_supported_models
  File "/usr/local/lib/python3.10/dist-packages/mii/legacy/__init__.py", line 7, in <module>
    from .client import MIIClient, mii_query_handle
  File "/usr/local/lib/python3.10/dist-packages/mii/legacy/client.py", line 12, in <module>
    from .method_table import GRPC_METHOD_TABLE
  File "/usr/local/lib/python3.10/dist-packages/mii/legacy/method_table.py", line 8, in <module>
    from transformers import Conversation
ImportError: cannot import name 'Conversation' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

**Comment by tang-t21** [comment]
Need to use an older version of transformer, but 'pip install deepspeed-mii' installs the latest one.

**Comment by zyyyyy5** [comment]
> Need to use an older version of transformer, but 'pip install deepspeed-mii' installs the latest one.

I encountered this issue too. May I ask which version of transformer you use?

**Comment by loadams** [comment]
Hi @tang-t21 - this is resolved in the latest source builds of DeepSpeed-MII here https://github.com/microsoft/DeepSpeed-MII/pull/492.  But we have not done a new release of MII that contains these fixes.  We will work on this and update you when this is done soon.

**Comment by loadams** [comment]
@tang-t21 - this is resolved in the latest release of DeepSpeed MII.  If you hit any issues, please let us know and we can re-open this issue.
