### ISSUE TITLE
Multiple people querying MII issue

### ISSUE THREAD

**Issue by mayank31398** [microsoft/DeepSpeed-MII#54]
I have an issue
If multiple people query a model deployed via MII, I run into event loop is already running error.

@jeffra

**Comment by mayank31398** [comment]
Do you have any ideas on how to fix this?

**Comment by cderinbogaz** [comment]
Would it make sense to put a queue in front of the server? Not a neat solution but this is the first thing I can think of

**Comment by mayank31398** [comment]
Not really, since the scripts are not only supporting DS-inference but HF-accelerate and DS-ZeRO too.
But, I have identified where changes can be made in MIIServerClient class.
Not sure if the changes are needed in MII repo itself, maybe I can extend that class.
Will update here if I run into problems

**Comment by mayank31398** [comment]
nvm my solution did not work

**Comment by mayank31398** [comment]
The above linked PR will fix this in the server code https://github.com/huggingface/transformers-bloom-inference/pull/7
I believe that the change should not be made in MII.
Going through the MII code, I figured out the complexities of asyncio ops used for launching the generate method on multiple processes. Making changes to MII will make it even more complicated.
