### ISSUE TITLE
8x40GB GPU instance failing with bloom-deepspeed-inference-int8

### ISSUE THREAD

**Issue by TahaBinhuraib** [microsoft/DeepSpeed-MII#58]
int8 doesn't work. (DeepSpeed-MII) only has fp16 support for now. 
Any idea on when int8 will be supported?

**Comment by volkerha** [comment]
should be supported for bloom now since this commit: f29a6cad60da6f7c8cafc86346ed668d0e6b3327

**Comment by mrwyattii** [comment]
@TahaBinhuraib could you please try running again with the latest updates to MII? Closing the issue for now as we do support `int8` with the Bloom model. Please re-open if you see errors when deploying. Thanks!

**Comment by TahaBinhuraib** [comment]
Thank you very much!
