### ISSUE TITLE
Support for Salesforce/CodeGen

### ISSUE THREAD

**Issue by andrePankraz** [microsoft/DeepSpeed-MII#86]
Currently https://huggingface.co/Salesforce/codegen-16B-multi and smaller variantes are not supported.
It seems to be a standard text-generation transformer and may be it just doesn't work yet, because of the model-type constraints in SUPPORTED_MODEL_TYPES?
This doesn't match any of the supported model types: https://huggingface.co/api/models?filter=codegen&full=true

**Comment by mrwyattii** [comment]
Hi @andrePankraz , you are correct in that we don't have these models in our `SUPPORTED_MODEL_TYPES` [here](https://github.com/microsoft/DeepSpeed-MII/blob/81aca4db2fe8aab9ca8b62ce61464ff212b88722/mii/constants.py#L51)

However, I did just do a test with a locally modified MII that skips this check and the model you linked to does work. @jeffra @RezaYazdaniAminabadi any reason not to add the `codegen` models to our supported models? At the very least, adding an option to skip MII compatibility checks may be worthwhile.

**Comment by jeffra** [comment]
From a kernel acceleration perspective we support GPT-J, I recall seeing there’s a way to covert this codegen model to a GPT-J model. In short term you might try that? However, medium term I think it’s possible for us to adapt our injection policy to support this model. We’ll need to investigate this further though.

https://twitter.com/moyix/status/1551608934091341828?s=46&t=00FUkiOvSQ9s7sPwtFbDwA

if you don’t need kernel acceleration you can turn off the model checking via a new Mii config option: skip_model_check: true

https://github.com/microsoft/DeepSpeed-MII/blob/e6b48479b8ec362ee73eb89f4b349ca39141df66/mii/config.py#L17
