### ISSUE TITLE
DS-MII License query

### ISSUE THREAD

**Issue by mayank31398** [microsoft/DeepSpeed-MII#93]
Hi @mrwyattii ,
I am trying to create an inference solution for large models that has support for various frameworks like DS-inference, DS-ZeRO and standard HF codebase.

Is it fine, if I extend some of the classes in MII like MIIServerClient and borrow some pieces of code from the proto files?
This is the relevant PR: https://github.com/huggingface/transformers-bloom-inference/pull/25

**Comment by mrwyattii** [comment]
Hi @mayank31398 MII has an MIT license, which indicates you can reuse code for your own purposes (provided the copyright text is also included, I believe). However, I'm no expert on licensing... so @jeffra if this is wrong, please correct me :)

**Comment by mayank31398** [comment]
Wellm I am just re-using code in these 2 files:
https://github.com/huggingface/transformers-bloom-inference/blob/4fee9755090fe744ad1aebe1a860dc32064126a4/inference_server/model_handler/deployment.py
https://github.com/huggingface/transformers-bloom-inference/blob/4fee9755090fe744ad1aebe1a860dc32064126a4/inference_server/model_handler/grpc_utils/generation_server.py
The first one is just extending the class MIIServerClient.
and the second file is quite generic. Nothing special in it.

**Comment by jeffra** [comment]
Hi @mayank31398, Mike is right here we’re MIT license which allows this type of usage. Please do retain copyright at the top of the file and also if you could acknowledge DeepSpeed-MII in some way that would be greatly appreciated :)

Closing the issue for now but feel free to reopen if you would like.
