### ISSUE TITLE
Issue with default mii_cache location

### ISSUE THREAD

**Issue by xiang-deng** [microsoft/DeepSpeed-MII#95]
The default mii_cache location is hardcoded as `/tmp/cache`, and we run into issues in a cluster environment when multi-users are trying to submit jobs and write on that directory. Maybe it is better to make the default cache location respect the environment variable set in the system.
https://github.com/microsoft/DeepSpeed-MII/blob/81aca4db2fe8aab9ca8b62ce61464ff212b88722/mii/constants.py#L98

**Comment by mrwyattii** [comment]
Hi @xiang-deng you can modify the cache path by setting the `MII_CACHE_PATH` environment variable. This will take precedence over the default path:
https://github.com/microsoft/DeepSpeed-MII/blob/e31b3e24c058a36149fcc7e29986c57a6d04c892/mii/utils.py#L146

Does this address the issue you are seeing?

**Comment by xiang-deng** [comment]
Oh yeah, that resolves the issue. It was a little bit hard to locate where the path was specified in the beginning as we thought it was inherited somewhere.
